# Generated by Django 5.2.7 on 2025-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automático')], default='M', max_length=20),
        ),
    ]
